### ISSUE TITLE
ESP is always rebooting

### ISSUE THREAD

**Issue by appi1** [oh2mp/esp32_ble2mqtt#1]
I want to test your sw esp32_ble2mqtt for my mobile home.
The SPIFF files have uploaded but after flashing the SW I always get the following error
ESP: WeMos Mini D1 LOLIN32

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5816
entry 0x400806ac

ESP32 BLE2MQTT
Starting portal...Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x401f165f  PS      : 0x00060130  A0      : 0x800d4065  A1      : 0x3ffcf5b0  
A2      : 0x00000000  A3      : 0x3f401ddb  A4      : 0x00000000  A5      : 0x00000000  
A6      : 0x00000000  A7      : 0x00000002  A8      : 0x800812f6  A9      : 0x3ffcf590  
A10     : 0x00001195  A11     : 0x00000000  A12     : 0x00001195  A13     : 0x000055c0  
A14     : 0x3ffc6898  A15     : 0x00000001  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xfffffffb  

Backtrace: 0x401f165f:0x3ffcf5b0 0x400d4062:0x3ffcf5d0 0x400d46bb:0x3ffcf6a0 0x400e08c7:0x3ffcf740 0x4008e725:0x3ffcf760

Rebooting...
ets Jun  8 2016 00:22:57

Any Idee?

**Comment by oh2mp** [comment]
Thanks for report. Yes, i have an idea. To be honest I never tested that on "virgin" esp32, but I had always manually made configs uploaded. There's a bug that prevents it working if there are no config files. 

I will fix that but if you want it working immediately, create config files manually and upload them to SPIFFS.
Here are the instructions: https://github.com/oh2mp/esp32_ble2mqtt/blob/main/FORMATS.md

**Comment by oh2mp** [comment]
This is fixed now. Can you make a test too, please? At least it worked and started portal automatically now when I had no config files on SPIFFS.

**Comment by appi1** [comment]
Hey Miko

thank you for the quick fix. It work’s now. But the Wifi PW can be only 32 Character and i need more….  After this charcters 12345678912345678912345678912345 it’s finish.

greeting remo

 

Von: Mikko Pikarinen [mailto:notifications@github.com] 
Gesendet: Sonntag, 17. Januar 2021 13:54
An: oh2mp/esp32_ble2mqtt <esp32_ble2mqtt@noreply.github.com>
Cc: appi1 <remo.krucker@bluewin.ch>; Author <author@noreply.github.com>
Betreff: Re: [oh2mp/esp32_ble2mqtt] ESP is always rebooting (#1)

 

This is fixed now. Can you make a test too, please? At least it worked and started portal automatically now when I had no config files on SPIFFS.

**Comment by oh2mp** [comment]
Thanks for noticing that. The max length of WiFi passphrase is 63 chars according to WiFi specification. I fixed that too.
